Refactor
SBIOML/emager-py pull request #4
Opened 2024-05-20 19:32 UTC by Michiboi29

2024-05-21 07:30 UTC, gabrielpgagne requested changes
Overall, je pense qu'il faudrait restructurer pour que ça aie plus de cohésion. Puis de limiter la taille du repo en enlevant les fichiers binaires (modèles, images, audio) et en faisant des helpers pour pull ces dits fichiers lorsque nécessaire.

2024-05-30 07:04 UTC, gabrielpgagne requested changes
Au moment de merge, je propose aussi que tous les if __name__ == "__main__", on delete ça et ceux pertinents on les met dans les exemples

2024-05-30 12:54 UTC, Michiboi29 commented
je vais delete les fichiers inutiles et les if==main aussi et j'ai déjà plusieurs exemple que je trouve pertinant si tu pense a d'autre que tu aimerais rajouter tu peux me le dire si tu veux que j'en fasse un de plus. 
Quelques points précis a regarder:

1. J'ai complété realtime_prediction avec la lib emager_py
2. J'ai changé la fonction read de Serial streamer pour que le real time sois fonctionnel, mais il faudrait peut-etre plus que une fonction read. J'ai rajouter un wait avant la lecture pour que le thread de lecture ne prenne pas tout le CPU. Sinon le realtime crash. Je pensais aussi rajouter une read avec un temps specifique.
3. J'ai modifier screen_guided_trainning pour plus ressembler au data_record et new_recording (WIP)

2024-06-03 13:38 UTC, Michiboi29 commented
@gabrielpgagne j'ai pas mal fini j'entendrais juste ton review pour commencer à merge.

2024-06-05 18:43 UTC, gabrielpgagne reviewed
Avant que j'accepte de merge faudrait juste:
- git merge main into refactor (pour le module`torch/`) pis cleaner les `if __name__ == "__main__` de `torch`
- je renommerais data_processings à data, visualisation à visuali**z**ation, exemples à ex**a**mples, puis mettre tous les fichiers en snake_case (realtime_GUI -> realtime_gui), idem pour les exemples

2024-06-05 18:43 UTC, gabrielpgagne commented on emager_py/realtime_prediction.py
> +class HDEMG(object):
Est-ce que c'est un oubli de HDEMG?

2024-06-11 20:36 UTC, Michiboi29 commented
Les examples   
get_tripple_data.py , redis_remote_operations.py, redis_streamer.py, torch_models.py and virtual_tcp_streamer.py 
ne fonctionne pas

aussi build_dataflow.py je ne pense pas qu'il est à jour et je ne suis pas sur de ce qu'il devrais faire.

Je ne sais pas c'est quoi ton setup pour c'est examples la, mais il faudrait l'indiqué.

2024-06-17 17:33 UTC, Michiboi29 commented
@gabrielpgagne are we good to merge ?

2024-06-17 18:46 UTC, gabrielpgagne commented
> @gabrielpgagne Les examples get_tripple_data.py , redis_remote_operations.py, redis_streamer.py, torch_models.py and virtual_tcp_streamer.py ne fonctionne pas
> 
> aussi build_dataflow.py je ne pense pas qu'il est à jour et je ne suis pas sur de ce qu'il devrais faire.
> 
> Je ne sais pas c'est quoi ton setup pour c'est examples la, mais il faudrait l'indiqué.

Il semble que ces 4 exemples utilisent Redis. Si t'as pas un serveur Redis qui tourne sur ton ordi c'est sûr que ça marchera pas, j'vais aller mettre une note dans les scripts.

Build dataflow est outdated, mais c'est spécifique pour compiler un modèle pour FPGA so jusqu'à temps que Emager V2 soit up and running c'est correct.

2024-06-17 19:44 UTC, gabrielpgagne approved these changes
LGTM après ce comment là!

2024-06-17 19:44 UTC, gabrielpgagne commented on pyproject.toml
> +    "tensorflow-io-gcs-filesystem==0.31.0",
C'est quoi cette dépendance là? Elle brise `pdm update`

2024-06-17 20:01 UTC, Michiboi29 commented on pyproject.toml
> +    "tensorflow-io-gcs-filesystem==0.31.0",
ouin ça dependant de l'ordi ou pte la version de python que j'utilise j'ai pas le choix de l'avoir je suis pas certain pourquoi. J'ai pas tester avec tous les ordi mais sur le miens j'ai pas le choix de l'avoir sinon le pdm update marche pas

2024-06-17 20:15 UTC, Michiboi29 commented on pyproject.toml
> +    "tensorflow-io-gcs-filesystem==0.31.0",
je vais réessayé avec juste   "tensorflow>= 2.15", voir si je peux arrivé a enlevé l'autre dependances

2024-06-17 20:45 UTC, Michiboi29 commented on pyproject.toml
> +    "tensorflow-io-gcs-filesystem==0.31.0",
@gabrielpgagne ok je sais pas trop ce qui sais passé, masi maintenant ça marche sans   "tensorflow-io-gcs-filesystem==0.31.0", donc on peut l'enlevé i guess.

2024-06-17 20:56 UTC, gabrielpgagne commented
@Michiboi29 je te laisse merge ça si t'es prêt!

2024-06-17 20:59 UTC, merged